# Generated by Django 2.2.2 on 2019-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborationName', models.CharField(max_length=100, unique=True, verbose_name='Collaboration Name')),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
            },
        ),
        migrations.CreateModel(
            name='FrontendParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteHeading', models.CharField(default='4C DATABASE QUERY UTILITY', max_length=30, verbose_name='Site Heading')),
                ('frontHeading', models.CharField(default='Welcome', help_text='This is the large message on the front page', max_length=100, verbose_name='Front page message')),
                ('frontMessage', models.TextField(default='This system is designed to query 4C members for collaboration on projects.', help_text='This is the long informational text on the front page', verbose_name='Welcome long text')),
                ('frontMessageSubText', models.TextField(default='If you would like to be added to this database, please contact CONTACT NAME.', help_text='This is the second long informational text on the front page', verbose_name='Front Page long text sub message')),
                ('additionEmailAddress', models.EmailField(default='add@centralcoastclimate.org', max_length=254, verbose_name='Database Addition Email Address')),
                ('commitBranch', models.CharField(max_length=100)),
                ('commitHash', models.CharField(max_length=100)),
                ('commitMessage', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'FrontendParameters',
                'verbose_name_plural': 'Front End Parameters',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywordType', models.CharField(choices=[('TK', 'Topical Keyword'), ('AK', 'Activity Keyword')], max_length=2, verbose_name='Keyword Type')),
                ('sortOrder', models.CharField(choices=[('HS', 'High Level'), ('MS', 'Medium Level'), ('LS', 'Low Level')], help_text='How high level is this keyword? (Fruit would be high level,          Apple would be medium level, and Fuji Apple would be low level.', max_length=2, verbose_name='Sort Order')),
                ('keywordName', models.CharField(max_length=100, unique=True, verbose_name='Keyword Name')),
                ('keywordDescription', models.TextField(blank=True, help_text='A short, optional description of the keyword.', null=True, verbose_name='Description')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('orgType', models.CharField(choices=[('IO', 'Institution'), ('CY', 'City'), ('CO', 'County'), ('NG', 'NGO'), ('RA', 'Regional Agency')], default=2, max_length=2, verbose_name='Organization Type')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department Name')),
                ('dateAdded', models.DateTimeField(auto_now_add=True, null=True)),
                ('orgNameUnique', models.CharField(help_text="Don't change this value, it is automatically generated.", max_length=100)),
            ],
            options={
                'unique_together': {('orgName', 'department')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('US', 'University Faculty/Staff'), ('CS', 'City Staff'), ('CO', 'County Staff'), ('NS', 'NGO Staff'), ('RS', 'Regional Staff')], max_length=2, verbose_name='User Type')),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('jobTitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title')),
                ('emailAddress', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('collaborations', models.ManyToManyField(blank=True, to='c4Backend.Collaborations', verbose_name='Collaborations')),
                ('keywords', models.ManyToManyField(to='c4Backend.Keyword', verbose_name='Keywords')),
                ('organization', models.ManyToManyField(to='c4Backend.Organization', verbose_name='Affiliated Organization')),
            ],
        ),
    ]
