# Generated by Django 2.2.1 on 2019-05-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywordType', models.CharField(choices=[('TK', 'Topical Keyword'), ('AK', 'Activity Keyword')], max_length=2, verbose_name='Keyword Type')),
                ('sortOrder', models.CharField(choices=[('HS', 'High Level'), ('MS', 'Medium Level'), ('LS', 'Low Level')], help_text='How high level is this keyword?', max_length=2, verbose_name='Sort Order')),
                ('keywordName', models.CharField(max_length=100, verbose_name='Keyword Name')),
                ('keywordDescription', models.TextField(verbose_name='A short, optional description of the keyword.')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('orgType', models.CharField(choices=[('IO', 'Institution'), ('CY', 'City'), ('NS', 'Not Set')], default=2, max_length=2, verbose_name='Organization Type')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('4C', '4C Faculty/Staff'), ('CS', 'City Staff')], max_length=2, verbose_name='User Type')),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('emailAddress', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('website', models.URLField(verbose_name='Website')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Short Description')),
                ('keywords', models.ManyToManyField(to='c4Backend.Keyword', verbose_name='Keywords')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c4Backend.Organization', verbose_name='Affiliated Organization')),
            ],
        ),
    ]
