# Generated by Django 2.2.1 on 2019-05-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobTitle',
            field=models.CharField(default='NA', max_length=100, verbose_name='Job Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('US', 'University Faculty/Staff'), ('CS', 'City Staff')], max_length=2, verbose_name='User Type'),
        ),
    ]
