# Generated by Django 2.2.1 on 2019-06-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keywordType',
            field=models.CharField(max_length=2, verbose_name='Keyword Type'),
        ),
    ]
