# Generated by Django 2.2.3 on 2019-07-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborations',
            options={'ordering': ['collaborationName'], 'verbose_name': 'Collaboration', 'verbose_name_plural': 'Collaborations'},
        ),
        migrations.AlterModelOptions(
            name='frontendparameters',
            options={'verbose_name': 'Frontend Parameters', 'verbose_name_plural': 'Front End Parameters'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['keywordType', 'keywordName'], 'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['orgName', 'department'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['lastName', 'firstName'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgNameUnique',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(to='c4Backend.Organization', verbose_name='Affiliated Organization(s)'),
        ),
    ]
