# Generated by Django 2.2.1 on 2019-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0002_auto_20190521_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keywordDescription',
            field=models.TextField(blank=True, verbose_name='A short, optional description of the keyword.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jobTitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
