# Generated by Django 2.2.1 on 2019-05-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0003_auto_20190521_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keywordDescription',
            field=models.TextField(blank=True, help_text='A short, optional description of the keyword.', verbose_name='Description'),
        ),
    ]
