# Generated by Django 2.2.1 on 2019-05-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0004_auto_20190521_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='orgType',
            field=models.CharField(choices=[('IO', 'Institution'), ('CY', 'City')], default=2, max_length=2, verbose_name='Organization Type'),
        ),
    ]
