# Generated by Django 2.2.1 on 2019-06-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0004_auto_20190620_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collaborations',
            field=models.ManyToManyField(blank=True, null=True, to='c4Backend.Collaborations', verbose_name='Collaborations'),
        ),
    ]
