# Generated by Django 2.2.1 on 2019-06-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0006_auto_20190620_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='orgNameUnique',
            field=models.CharField(default='tbd', max_length=100),
            preserve_default=False,
        ),
    ]
