# Generated by Django 2.2.1 on 2019-05-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0008_auto_20190523_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keywordName',
            field=models.CharField(max_length=100, unique=True, verbose_name='Keyword Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgName',
            field=models.CharField(max_length=100, unique=True, verbose_name='Organization Name'),
        ),
    ]
