# Generated by Django 2.2.1 on 2019-06-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0009_auto_20190523_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='orgName',
            field=models.CharField(max_length=100, verbose_name='Organization Name'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('orgName', 'department')},
        ),
    ]
