# Generated by Django 2.2.1 on 2019-06-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0011_auto_20190603_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='orgType',
            field=models.CharField(choices=[('IO', 'Institution'), ('CY', 'City'), ('CO', 'County'), ('NG', 'NGO'), ('RE', 'Regional')], default=2, max_length=2, verbose_name='Organization Type'),
        ),
    ]
