# Generated by Django 2.2.1 on 2019-06-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0013_auto_20190611_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('US', 'University Faculty/Staff'), ('CS', 'City Staff'), ('CO', 'County Staff'), ('NS', 'NGO Staff'), ('RS', 'Regional Staff')], max_length=2, verbose_name='User Type'),
        ),
    ]
