# Generated by Django 2.2.1 on 2019-06-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0014_auto_20190611_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborationName', models.CharField(max_length=100, unique=True, verbose_name='Collaboration Name')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='collaborations',
            field=models.ManyToManyField(to='c4Backend.Collaborations', verbose_name='Collaborations'),
        ),
    ]
