# Generated by Django 2.2.2 on 2019-06-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0015_auto_20190611_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborations',
            options={'verbose_name': 'Collaboration', 'verbose_name_plural': 'Collaborations'},
        ),
    ]
