# Generated by Django 2.2.3 on 2019-07-15 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c4Backend', '0016_auto_20190616_2023'),
        ('c4Backend', '0007_organization_orgnameunique'),
    ]

    operations = [
    ]
